language: objective-c
os: osx
osx_image: xcode12.0
xcode_scheme: TMDB
xcode_workspace: TMDB.xcworkspace
xcode_destination: platform=iOS Simulator,OS=13.5,name=iPhone 11
install:
  - bundle install
script:
  - bundle exec fastlane tests
after_success:
 - bash <(curl -s https://codecov.io/bash)
