language: objective-c
os: osx
osx_image: xcode11.5
xcode_scheme: TMDB
xcode_workspace: TMDB.xcworkspace
xcode_destination: platform=iOS Simulator,OS=13.5,name=iPhone 11
install:
  - bundle install
script:
  - fastlane beta
